#!/bin/sh

if [ ! -e $DOTFILES/vim/bundle/vundle ]; then
  curl https://raw.githubusercontent.com/Shougo/neobundle.vim/master/bin/install.sh | sh
fi
vim -u $DOTFILES/vim/vimrc.bundles +NeoBundleInstall +qall
