#!/usr/local/bin/fish

if test ! -e $HOME/.vim/bundle/neobundle.vim
  curl https://raw.githubusercontent.com/Shougo/neobundle.vim/master/bin/install.sh | sh
end
vim -u $DOTFILES/vim/bundles.vim +NeoBundleInstall +qall
