#!/bin/sh

export dotfiles="$HOME/.dotfiles"

# # Install RVM if it's not already installed
# if [ ! -s "$HOME/.rvm/scripts/rvm" ]; then
#   gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
#   curl -sSL https://get.rvm.io | bash -s stable --ruby
#   source "$HOME/.rvm/scripts/rvm"
#
#   exec "rvm @global do gem install pry terminal-notifier foreman pry-doc t"
# fi
#
# # Install NVM if it's not already installed
# if [ ! -s "$HOME/.nvm/nvm.sh" ]; then
#   curl https://raw.githubusercontent.com/creationix/nvm/v0.24.0/install.sh | bash
#   source "$HOME/.nvm/nvm.sh"
#   nvm install 0.12
#   nvm alias default 0.12
#   npm install --global bower gulp mocha
# fi
