#!/bin/sh

export dotfiles="$HOME/.dotfiles"

# Install RVM if it's not already installed
if [ ! -s "$HOME/.rvm/scripts/rvm" ]; then
  curl -sSL https://get.rvm.io | bash -s stable --ruby
  source "$HOME/.rvm/scripts/rvm"

  exec "rvm @global do gem install pry terminal-notifier foreman"
fi

# Install NVM if it's not already installed
if [ ! -s "$HOME/.nvm/nvm.sh" ]; then
  curl https://raw.githubusercontent.com/creationix/nvm/v0.13.1/install.sh | bash
  source "$HOME/.nvm/nvm.sh"
  nvm install 0.10
  nvm alias default 0.10
  npm install --global trash bower gulp mocha
fi
